# Generated by Django 4.0.6 on 2022-08-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0005_article_slug_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
    ]
